### ISSUE TITLE
Method matches of JsonContains must return bool

### ISSUE THREAD

**Issue by mishatrinex** [Codeception/phpunit-wrapper#42]
https://github.com/Codeception/phpunit-wrapper/blob/a4990126a20bbaa67ca34088ff91960c209a664b/src/Constraint/JsonContains.php#L45
Method returns nothing if assertEquals didn't throw an exception, but boolean is expected. I think this part should be:
```php
try {
    $comparator->assertEquals($this->expected, $jsonResponseArray->toArray());
} catch (ComparisonFailure $failure) {
    throw new \PHPUnit\Framework\ExpectationFailedException(
        "Response JSON does not contain the provided JSON\n",
        $failure
    );
}

return true;
```

**Comment by Naktibalda** [comment]
You are welcome to make this change to please static analyzers.

Missing return doesn't cause any issues, because `true` is returned few lines higher: https://github.com/Codeception/phpunit-wrapper/blob/a4990126a20bbaa67ca34088ff91960c209a664b/src/Constraint/JsonContains.php#L38-L39

That exception is throw on 100% of calls to assertEquals, because ArrayComparator is used to produce concise diff output.

**Comment by mishatrinex** [comment]
>That exception is throw on 100% of calls to assertEquals, because ArrayComparator is used to produce concise diff output.

There is the case when `ArrayComparator` doesn't throw any exception:
```php
<?php

namespace tests\codeception\api\site;

use ApiTester;
use Codeception\PHPUnit\Constraint\JsonContains;


class TestCest extends AbstractApiSiteCest
{
    /**
     * @env site
     *
     * @param ApiTester $I
     */
    public function testContains(ApiTester $I): void
    {
        \PHPUnit\Framework\Assert::assertThat(
            \json_encode($this->getArray()),
            new JsonContains(
                $this->getExpected()
            )
        );
    }

    /**
     * Expected array
     *
     * @return array
     */
    private function getExpected(): array
    {
        return ['key' => true];
    }

    /**
     * Testing array
     *
     * @return array
     */
    private function getArray(): array
    {
        return ['key' => 1];
    }

}

```
So result is: 
`[TypeError] Return value of Codeception\PHPUnit\Constraint\JsonContains::matches() must be of the type boolean, none returned`. 
The problem is that the wrong comparison is used here (`!=` instead of `!== `):
https://github.com/sebastianbergmann/comparator/blob/5de4fc177adf9bce8df98d8d141a7559d7ccf6da/src/ScalarComparator.php#L75

Anyway, returning `true` in the end of `matches`  is not correct behavior in my case.

**Comment by Naktibalda** [comment]
return false would be correct if Comparator missed it.

**Comment by mishatrinex** [comment]
Or throw exception `\PHPUnit\Framework\ExpectationFailedException` in finally block?

**Comment by Naktibalda** [comment]
try both options and compare results.
