### ISSUE TITLE
Update phpunit dependency to 7.4

### ISSUE THREAD

**Issue by Y0lk** [Codeception/phpunit-wrapper#46]
A few months ago, the phpunit dependency was changed to be more strict, but now phpunit 7.4 is out. For projects that have phpunit listed as a dependency without the same strict rule, it causes codeception/phpunit-wrapper to revert back to version 7.1. Not sure if this is a better option.

If anything, would be great if this package could be updated to support phpunit 7.4 so that it doesn't revert back to 7.1 in cases like the one I just described. 7.4 doesn't have any breaking changes.

**Comment by Naktibalda** [comment]
7.5 will be out next Friday, so it would be better to support it too.
https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-7.5.md

Also Sebastian deprecated a lot of methods,
so supporting PhpUnit 9 will require a lot of work.
