### ISSUE TITLE
The v7 version of phpunit-wrapper is incompatible with phpunit 7

### ISSUE THREAD

**Issue by cosminardeleanu** [Codeception/phpunit-wrapper#6]
The reason lies in this commit -> https://github.com/sebastianbergmann/phpunit/commit/7e9e3aa43de9d684bfa5b8b87b137992b4366e6c 

Please update, and make it compatible with phpunit ~7, or rollback the dependency to phpunit ~6.

```Error example
Codeception PHP Testing Framework v2.4.0
Powered by PHPUnit 7.0.2 by Sebastian Bergmann and contributors.
PHP Fatal error:  Declaration of Codeception\PHPUnit\ResultPrinter\Report::endTest(PHPUnit\Framework\Test $test, $time) must be compatible with PHPUnit\Util\TestDox\ResultPrinter::endTest(PHPUnit\Framework\Test $test, float $time): void in ../vendor/codeception/phpunit-wrapper/src/ResultPrinter/Report.php on line 9
```

**Comment by DavertMik** [comment]
Thanks! Looks like I missed that exact one file as all other reporters were upgraded
That's actually the reasons there are 2 branches in this package to keep different interfaces for different PHPUnits

But anyway... Do you really need that `Report` result printer?

**Comment by DavertMik** [comment]
Fixed
