### ISSUE TITLE
Invalid JsonType reference 

### ISSUE THREAD

**Issue by countless-integers** [Codeception/phpunit-wrapper#79]
I've been trying to use `JsonType`, but it appears that since codeception v4 this is no longer possible. There's no documentation reference to what happened to it, only the release diff shows it was removed. I found a class in this repo with the same name, but it features a [reference](https://github.com/Codeception/phpunit-wrapper/blob/9.0/src/Constraint/JsonType.php#L5) to that removed class from main codeception repo:

```
use Codeception\Util\JsonType as JsonTypeUtil;
```

Do you guys know what happened to that class?

**Comment by Naktibalda** [comment]
It was moved to module-rest repository: https://github.com/Codeception/module-rest/blob/master/src/Codeception/Util/JsonType.php

**Comment by countless-integers** [comment]
Thanks! I wish it was a separate library somehow, but that's a different issue.
